apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/godwindockerid/udagram-api-user:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m